# Generated by Django 3.0.8 on 2020-07-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbuns',
            },
        ),
        migrations.CreateModel(
            name='Bandas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Bandas')),
            ],
            options={
                'verbose_name': 'Banda',
                'verbose_name_plural': 'Bandas',
                'ordering': ['-nome'],
            },
        ),
        migrations.CreateModel(
            name='Musicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Musica')),
                ('segundos', models.IntegerField(verbose_name='Segundos')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disco.Albuns', verbose_name='Álbum')),
            ],
        ),
        migrations.AddField(
            model_name='albuns',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disco.Bandas', verbose_name='Banda'),
        ),
    ]
