# Generated by Django 3.0.8 on 2020-07-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicas',
            options={'ordering': ['-titulo'], 'verbose_name': 'Musica', 'verbose_name_plural': 'Musicas'},
        ),
    ]
